- name: Installing web packages
  hosts: all
  vars:
    - webPage: "saba.html"
    - packageName: "httpd"
    - documentDir: "/var/www/linuxworld"

  tasks:
  - name: Installing httpd package
    package: 
         name: "{{ packageName }}" 
         state: present

  - name: Copying html artifact
    copy:
       src: "{{ webPage }}"
       dest: "{{ documentDir }}"

  - name: Restart the httpd service 
    service:
        name: httpd
        state: started

